# Generated by Django 4.2.7 on 2024-03-19 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_profile_address_profile_city_profile_prov"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="address",
            field=models.CharField(default="10220 104 Ave NW", max_length=100),
        ),
        migrations.AlterField(
            model_name="profile",
            name="city",
            field=models.CharField(default="Edmonton", max_length=15),
        ),
        migrations.AlterField(
            model_name="profile",
            name="prov",
            field=models.CharField(default="AB", max_length=5),
        ),
    ]
