# Generated by Django 4.2.7 on 2024-03-28 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catches", "0090_lake_regions_region_lakes_delete_userregion"),
        ("users", "0007_alter_profile_address_alter_profile_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="regions",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="catches.region",
            ),
            preserve_default=False,
        ),
    ]
