# Generated by Django 4.2.7 on 2024-03-29 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_profile_regions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="regions",
        ),
    ]
