# Generated by Django 4.2.7 on 2024-04-16 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_remove_profile_regions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="/public/assets/catches/site/default_profile.jpg",
                upload_to="profile_pics",
            ),
        ),
    ]
