# Generated by Django 4.2.7 on 2024-04-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_alter_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="profile_pics/default_profile.jpg", upload_to="profile_pics"
            ),
        ),
    ]
