# Generated by Django 4.1.7 on 2023-04-03 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nhl', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Conferences',
            new_name='Conference',
        ),
        migrations.RenameModel(
            old_name='Divisions',
            new_name='Division',
        ),
        migrations.RenameModel(
            old_name='Teams',
            new_name='Team',
        ),
        migrations.RenameField(
            model_name='division',
            old_name='conferences',
            new_name='conference',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='divisions',
            new_name='division',
        ),
    ]
