# Generated by Django 4.1.7 on 2023-04-04 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nhl', '0002_rename_conferences_conference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('nhl_id', models.IntegerField()),
                ('jersey', models.IntegerField()),
                ('birthDate', models.DateTimeField()),
                ('nationality', models.CharField(max_length=100)),
                ('height', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=100)),
                ('active', models.BooleanField()),
                ('alternateCaptain', models.BooleanField()),
                ('captain', models.BooleanField()),
                ('rookie', models.BooleanField()),
                ('shootsCatches', models.CharField(max_length=100)),
                ('rosterStatus', models.BooleanField()),
                ('primaryPosition', models.CharField(max_length=100)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nhl.team')),
            ],
            options={
                'ordering': ['jersey'],
            },
        ),
    ]
