# Generated by Django 4.1.7 on 2023-04-04 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhl', '0003_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='rosterStatus',
            field=models.CharField(max_length=10),
        ),
    ]
