# Generated by Django 4.1.3 on 2023-01-04 17:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='date',
            field=models.DateField(default=datetime.date(2023, 1, 4)),
        ),
    ]
