# Generated by Django 4.1.3 on 2023-01-04 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insects', '0003_alter_week_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='temp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='insects.temp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log',
            name='week',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='insects.week'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='week',
            name='temperatures',
            field=models.ManyToManyField(through='insects.Log', to='insects.temp'),
        ),
    ]
