# Generated by Django 4.1.3 on 2023-01-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insects', '0004_log_temp_log_week_week_temperatures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='week',
            name='temperatures',
        ),
        migrations.AddField(
            model_name='temp',
            name='temperatures',
            field=models.ManyToManyField(through='insects.Log', to='insects.week'),
        ),
    ]
