# Generated by Django 4.1.3 on 2023-01-04 17:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('insects', '0005_remove_week_temperatures_temp_temperatures'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Insect name')),
            ],
        ),
        migrations.AddField(
            model_name='log',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Bug_site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('bug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insects.bug')),
                ('temp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insects.temp')),
            ],
        ),
    ]
