# Generated by Django 4.1.3 on 2023-01-04 17:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('insects', '0006_bug_log_date_bug_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('bug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insects.bug')),
            ],
        ),
    ]
