# Generated by Django 4.1.3 on 2023-01-04 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insects', '0008_hatch_weeks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug_site',
            name='name',
        ),
    ]
