# Generated by Django 4.1.3 on 2023-01-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insects', '0009_remove_bug_site_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='week',
            name='date',
        ),
        migrations.AddField(
            model_name='week',
            name='number',
            field=models.IntegerField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
