# Generated by Django 4.1.3 on 2023-01-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insects', '0010_remove_week_date_week_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='number',
            field=models.IntegerField(),
        ),
    ]
