# Generated by Django 4.1.3 on 2023-01-04 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insects', '0011_alter_week_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug_site',
            name='week',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='insects.week'),
            preserve_default=False,
        ),
    ]
