# Generated by Django 4.1.3 on 2023-01-05 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insects', '0013_alter_bug_site_bug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug_site',
            name='bug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sightings', to='insects.bug'),
        ),
        migrations.AlterField(
            model_name='bug_site',
            name='temp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorded_temps', to='insects.temp'),
        ),
        migrations.AlterField(
            model_name='bug_site',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='insects.week'),
        ),
        migrations.AlterField(
            model_name='hatch',
            name='bug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insect', to='insects.bug'),
        ),
        migrations.AlterField(
            model_name='log',
            name='temp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='insects.temp'),
        ),
        migrations.AlterField(
            model_name='log',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorded_temps', to='insects.week'),
        ),
    ]
