# Generated by Django 4.1.3 on 2023-01-05 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insects', '0014_alter_bug_site_bug_alter_bug_site_temp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temp',
            old_name='temperatures',
            new_name='week_numbers',
        ),
    ]
