# Generated by Django 4.1.3 on 2023-01-05 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insects', '0015_rename_temperatures_temp_week_numbers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug_site',
            name='temp',
        ),
        migrations.RemoveField(
            model_name='bug_site',
            name='week',
        ),
    ]
