# Generated by Django 4.1.3 on 2023-01-05 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insects', '0016_remove_bug_site_temp_remove_bug_site_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temp',
            name='week_numbers',
        ),
        migrations.AddField(
            model_name='bug_site',
            name='temp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recorded_temps', to='insects.temp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bug_site',
            name='week',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='insects.week'),
            preserve_default=False,
        ),
    ]
