# Generated by Django 4.1.3 on 2023-01-05 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insects', '0017_remove_temp_week_numbers_bug_site_temp_bug_site_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp',
            name='week_numbers',
            field=models.ManyToManyField(through='insects.Log', to='insects.week'),
        ),
    ]
