# Generated by Django 4.1.3 on 2023-01-05 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insects', '0020_alter_hatch_strength'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.IntegerField(choices=[('none', 0), ('few', 1), ('weak', 2), ('low', 3), ('lots', 4), ('abundent', 5)], default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='hatch',
            name='weeks',
        ),
        migrations.AddField(
            model_name='week',
            name='strength',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='insects.strength'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hatch',
            name='strength',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insects.strength'),
        ),
    ]
