# Generated by Django 4.1.3 on 2023-01-05 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insects', '0021_strength_remove_hatch_weeks_week_strength_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hatch',
            name='strength',
        ),
        migrations.RemoveField(
            model_name='week',
            name='strength',
        ),
        migrations.AddField(
            model_name='strength',
            name='hatch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='insects.hatch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='strength',
            name='week',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='insects.week'),
            preserve_default=False,
        ),
    ]
