# Generated by Django 4.1.3 on 2023-01-05 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insects', '0023_remove_strength_hatch_hatch_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hatch',
            name='week',
        ),
        migrations.AddField(
            model_name='hatch',
            name='strength',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='insects.strength'),
            preserve_default=False,
        ),
    ]
