# Generated by Django 4.1.3 on 2023-01-05 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insects', '0024_remove_hatch_week_hatch_strength'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hatch',
            name='strength',
        ),
        migrations.AddField(
            model_name='hatch',
            name='week',
            field=models.ManyToManyField(through='insects.Strength', to='insects.week'),
        ),
        migrations.AddField(
            model_name='strength',
            name='hatch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='insects.hatch'),
            preserve_default=False,
        ),
    ]
