# Generated by Django 4.1.3 on 2023-01-05 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insects', '0025_remove_hatch_strength_hatch_week_strength_hatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strength',
            name='strength',
            field=models.IntegerField(choices=[(0, 'none'), (1, 'few'), (2, 'weak'), (3, 'low'), (4, 'lots'), (5, 'abundent')], default=0),
        ),
    ]
