# Generated by Django 4.1.3 on 2023-01-06 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insects', '0026_alter_strength_strength'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strength',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week', to='insects.week'),
        ),
    ]
