# Generated by Django 4.1.3 on 2023-01-09 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insects', '0027_alter_strength_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strength',
            name='hatch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strength_of_hatch', to='insects.hatch'),
        ),
    ]
