# Generated by Django 4.1.3 on 2022-12-09 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0002_movie_character'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Character',
        ),
        migrations.DeleteModel(
            name='Child',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
    ]
