# Generated by Django 4.1.3 on 2022-12-09 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0006_remove_registration_child_remove_registration_team_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fly',
            name='bug',
        ),
        migrations.RemoveField(
            model_name='lake',
            name='fish',
        ),
        migrations.RemoveField(
            model_name='log',
            name='fish',
        ),
        migrations.RemoveField(
            model_name='log',
            name='fly',
        ),
        migrations.RemoveField(
            model_name='log',
            name='lake',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='fish',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='lake',
        ),
        migrations.DeleteModel(
            name='Bug',
        ),
        migrations.DeleteModel(
            name='Fish',
        ),
        migrations.DeleteModel(
            name='Fly',
        ),
        migrations.DeleteModel(
            name='Lake',
        ),
        migrations.DeleteModel(
            name='Log',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
