# Generated by Django 4.1.3 on 2022-12-09 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catches', '0007_remove_fly_bug_remove_lake_fish_remove_log_fish_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bug', models.ManyToManyField(blank=True, to='catches.bug')),
            ],
        ),
        migrations.CreateModel(
            name='Fly_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catches.fish')),
                ('lake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catches.lake')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catches.fish')),
                ('fly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catches.fly')),
                ('lake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catches.lake')),
                ('temp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catches.temp')),
            ],
        ),
        migrations.AddField(
            model_name='lake',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catches.region'),
        ),
        migrations.AddField(
            model_name='fly',
            name='fly_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catches.fly_type'),
        ),
        migrations.CreateModel(
            name='Bug_site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catches.bug')),
                ('lake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catches.lake')),
                ('temp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catches.temp')),
            ],
        ),
    ]
