# Generated by Django 4.1.3 on 2022-12-09 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0009_alter_bug_site_temp_alter_fly_fly_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug_site',
            name='bug',
        ),
        migrations.RemoveField(
            model_name='bug_site',
            name='lake',
        ),
        migrations.RemoveField(
            model_name='bug_site',
            name='temp',
        ),
        migrations.RemoveField(
            model_name='fly',
            name='bug',
        ),
        migrations.RemoveField(
            model_name='fly',
            name='fly_type',
        ),
        migrations.RemoveField(
            model_name='lake',
            name='region',
        ),
        migrations.RemoveField(
            model_name='log',
            name='fish',
        ),
        migrations.RemoveField(
            model_name='log',
            name='fly',
        ),
        migrations.RemoveField(
            model_name='log',
            name='lake',
        ),
        migrations.RemoveField(
            model_name='log',
            name='temp',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='fish',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='lake',
        ),
        migrations.DeleteModel(
            name='Bug',
        ),
        migrations.DeleteModel(
            name='Bug_site',
        ),
        migrations.DeleteModel(
            name='Fish',
        ),
        migrations.DeleteModel(
            name='Fly',
        ),
        migrations.DeleteModel(
            name='Fly_type',
        ),
        migrations.DeleteModel(
            name='Lake',
        ),
        migrations.DeleteModel(
            name='Log',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.DeleteModel(
            name='Temp',
        ),
    ]
