# Generated by Django 4.1.3 on 2022-12-10 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0011_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='name',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='name',
        ),
    ]
