# Generated by Django 4.1.3 on 2022-12-11 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0013_alter_fly_author_alter_fly_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fly',
            name='bug',
        ),
        migrations.AddField(
            model_name='fly',
            name='bug',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catches.bug'),
        ),
    ]
