# Generated by Django 4.1.3 on 2022-12-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0015_alter_lake_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp',
            name='search_keys',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
