# Generated by Django 4.1.3 on 2022-12-14 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0016_temp_search_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='', verbose_name='Picture of catch'),
        ),
    ]
