# Generated by Django 4.1.3 on 2022-12-14 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0017_alter_log_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='fly',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catches.fly'),
        ),
    ]
