# Generated by Django 4.1.3 on 2022-12-14 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0018_alter_log_fly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='length',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='log',
            name='weight',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
