# Generated by Django 4.1.3 on 2022-12-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0019_alter_log_length_alter_log_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='article',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='bug',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Picture of insect'),
        ),
        migrations.AddField(
            model_name='fly_type',
            name='article',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='fly_type',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Picture of fly type'),
        ),
    ]
