# Generated by Django 4.1.3 on 2022-12-14 23:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0020_bug_article_bug_image_fly_type_article_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('author', models.TextField(blank=True)),
                ('url', models.URLField()),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('tag', models.ManyToManyField(to='catches.tag')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
