# Generated by Django 4.1.3 on 2022-12-15 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0022_alter_video_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fly',
            name='youtube',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catches.video'),
        ),
    ]
