# Generated by Django 4.1.3 on 2022-12-16 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0023_alter_fly_youtube'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
