# Generated by Django 4.1.3 on 2022-12-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0027_bug_tag_name_bug_youtube_fish_tag_name_fish_youtube_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='youtube',
        ),
        migrations.RemoveField(
            model_name='fish',
            name='youtube',
        ),
        migrations.RemoveField(
            model_name='fly',
            name='youtube',
        ),
        migrations.RemoveField(
            model_name='lake',
            name='youtube',
        ),
        migrations.AddField(
            model_name='fly',
            name='tag_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='video',
            name='fly',
            field=models.ManyToManyField(blank=True, to='catches.fly'),
        ),
        migrations.AlterField(
            model_name='bug',
            name='tag_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='fish',
            name='tag_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='lake',
            name='tag_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
