# Generated by Django 4.1.3 on 2022-12-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0030_video_fish'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug_site',
            name='tag_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
