# Generated by Django 4.1.3 on 2022-12-17 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0032_alter_log_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Picture of catch'),
        ),
    ]
