# Generated by Django 4.1.3 on 2022-12-17 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0034_alter_log_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='image',
        ),
    ]
