# Generated by Django 4.1.3 on 2022-12-17 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0035_remove_log_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fly',
            name='tag_name',
            field=models.CharField(default='tying', max_length=100),
        ),
    ]
