# Generated by Django 4.1.3 on 2022-12-17 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0036_alter_fly_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fly',
            name='tag_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
