# Generated by Django 4.1.3 on 2022-12-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0038_remove_bug_article_remove_bug_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fly_type',
            name='article',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='fly_type',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Picture of fly type'),
        ),
    ]
