# Generated by Django 4.1.3 on 2022-12-26 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0039_fly_type_article_fly_type_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fly_type',
            name='article',
        ),
    ]
