# Generated by Django 4.1.3 on 2022-12-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0040_remove_fly_type_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Picture of fly type'),
        ),
    ]
