# Generated by Django 4.1.3 on 2022-12-27 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0042_fly_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='fish',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Picture of the bug'),
        ),
        migrations.AlterField(
            model_name='bug',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Picture of the bug'),
        ),
    ]
