# Generated by Django 4.1.3 on 2022-12-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0043_fish_image_alter_bug_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='fish/', verbose_name='Picture of the bug'),
        ),
    ]
