# Generated by Django 4.1.3 on 2022-12-28 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0044_alter_fish_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='bug/', verbose_name='Picture of the bug'),
        ),
        migrations.AlterField(
            model_name='fly',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='flys/'),
        ),
        migrations.AlterField(
            model_name='fly_type',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='fly_type/', verbose_name='Picture of fly type'),
        ),
    ]
