# Generated by Django 4.1.3 on 2022-12-29 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0045_alter_bug_image_alter_fly_image_alter_fly_type_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fly',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='flys/'),
        ),
    ]
