# Generated by Django 4.1.3 on 2022-12-29 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0046_alter_fly_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fly',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='flys/'),
        ),
    ]
