# Generated by Django 4.1.3 on 2022-12-29 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0048_log_fish_swami'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='num_landed',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
