# Generated by Django 4.1.3 on 2022-12-30 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0049_log_num_landed'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp',
            name='deg',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temp',
            name='direction',
            field=models.CharField(default='down', max_length=10),
            preserve_default=False,
        ),
    ]
