# Generated by Django 4.1.3 on 2022-12-30 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0050_temp_deg_temp_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='fish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catches.fish'),
        ),
    ]
