# Generated by Django 4.1.3 on 2022-12-30 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0051_alter_log_fish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='temp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catches.temp'),
        ),
    ]
