# Generated by Django 4.1.3 on 2023-01-09 23:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0052_alter_log_temp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insect', to='catches.bug')),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='bug_site',
            name='name',
        ),
        migrations.AddField(
            model_name='bug_site',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Strength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.IntegerField(choices=[(0, 'none'), (1, 'few'), (2, 'weak'), (3, 'low'), (4, 'lots'), (5, 'abundent')], default=0)),
                ('hatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strength_of_hatch', to='catches.hatch')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week', to='catches.week')),
            ],
        ),
        migrations.AddField(
            model_name='hatch',
            name='week',
            field=models.ManyToManyField(through='catches.Strength', to='catches.week'),
        ),
        migrations.AddField(
            model_name='bug_site',
            name='week',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='catches.week'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log',
            name='week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catches.week'),
        ),
        migrations.AddField(
            model_name='temp',
            name='week_numbers',
            field=models.ManyToManyField(through='catches.Log', to='catches.week'),
        ),
    ]
