# Generated by Django 4.1.3 on 2023-01-11 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0052_alter_log_temp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bug_site',
        ),
    ]
