# Generated by Django 4.1.3 on 2023-01-11 21:03

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0053_delete_bug_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('notes', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('static_tag', models.SlugField()),
                ('bug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catches.bug')),
                ('lake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catches.lake')),
                ('temp', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='catches.temp')),
            ],
            options={
                'ordering': ['temp'],
            },
        ),
    ]
