# Generated by Django 4.1.3 on 2023-01-11 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0054_hatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.IntegerField(choices=[(0, 'none'), (1, 'few'), (2, 'weak'), (3, 'low'), (4, 'lots'), (5, 'abundent')], default=0)),
                ('hatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strength_of_hatch', to='catches.hatch')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week', to='catches.week')),
            ],
        ),
    ]
