# Generated by Django 4.1.3 on 2023-01-11 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0056_remove_chart_hatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='bug',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='insect', to='catches.bug'),
            preserve_default=False,
        ),
    ]
