# Generated by Django 4.1.3 on 2023-01-11 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0058_hatch_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='lake',
            name='week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catches.week'),
        ),
        migrations.AddField(
            model_name='log',
            name='week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catches.week'),
        ),
    ]
