# Generated by Django 4.1.3 on 2023-01-11 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0060_temp_week'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hatch',
            options={'ordering': ['week']},
        ),
        migrations.RemoveField(
            model_name='hatch',
            name='temp',
        ),
    ]
