# Generated by Django 4.1.3 on 2023-01-11 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0061_alter_hatch_options_remove_hatch_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hatch',
            name='name',
        ),
    ]
