# Generated by Django 4.1.3 on 2023-01-12 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0062_remove_hatch_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hatch',
            name='strength',
            field=models.IntegerField(choices=[(0, 'none'), (1, 'few'), (2, 'weak'), (3, 'low'), (4, 'lots'), (5, 'abundent')], default=0),
        ),
    ]
