# Generated by Django 4.1.3 on 2023-01-12 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0063_hatch_strength'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hatch',
            name='strength',
        ),
    ]
