# Generated by Django 4.1.3 on 2023-01-15 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0066_hatch_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='next_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='week',
            name='prev_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
