# Generated by Django 4.1.3 on 2023-01-16 17:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0067_week_next_num_week_prev_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='hatch',
            name='catch_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
