# Generated by Django 4.1.3 on 2023-01-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0069_rename_catch_date_hatch_sight_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='week',
            options={'ordering': ['number']},
        ),
        migrations.AlterField(
            model_name='log',
            name='num_landed',
            field=models.IntegerField(default=0),
        ),
    ]
