# Generated by Django 4.1.3 on 2023-01-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0070_alter_week_options_alter_log_num_landed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
