# Generated by Django 4.1.3 on 2023-01-31 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0071_alter_log_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='lake',
            name='gps_url',
            field=models.URLField(blank=True),
        ),
    ]
