# Generated by Django 4.1.3 on 2023-03-13 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0072_lake_gps_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
