# Generated by Django 4.1.3 on 2023-03-30 21:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0073_alter_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fly_type',
            name='notes',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
