# Generated by Django 4.2.7 on 2023-12-29 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catches", "0076_alter_lake_district"),
    ]

    operations = [
        migrations.AddField(
            model_name="lake",
            name="district_int",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
