# Generated by Django 4.2.7 on 2023-12-29 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catches", "0077_lake_district_int"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lake",
            name="district",
        ),
    ]
