# Generated by Django 4.2.7 on 2023-12-29 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catches", "0078_remove_lake_district"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lake",
            old_name="district_int",
            new_name="district",
        ),
    ]
