# Generated by Django 4.2.7 on 2023-12-30 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catches", "0079_rename_district_int_lake_district"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lake",
            name="lat",
            field=models.DecimalField(
                blank=True, decimal_places=14, max_digits=17, null=True
            ),
        ),
        migrations.AlterField(
            model_name="lake",
            name="long",
            field=models.DecimalField(
                blank=True, decimal_places=14, max_digits=17, null=True
            ),
        ),
    ]
