# Generated by Django 4.2.7 on 2023-12-30 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catches", "0080_alter_lake_lat_alter_lake_long"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lake",
            name="lat",
            field=models.DecimalField(
                blank=True, decimal_places=20, max_digits=25, null=True
            ),
        ),
        migrations.AlterField(
            model_name="lake",
            name="long",
            field=models.DecimalField(
                blank=True, decimal_places=20, max_digits=25, null=True
            ),
        ),
    ]
