# Generated by Django 4.2.7 on 2024-02-12 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catches", "0081_alter_lake_lat_alter_lake_long"),
    ]

    operations = [
        migrations.AlterField(
            model_name="region",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
