# Generated by Django 4.2.7 on 2024-03-13 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("catches", "0082_alter_region_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="log",
            name="angler",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="log",
            name="private",
            field=models.BooleanField(default=False),
        ),
    ]
