# Generated by Django 4.2.7 on 2024-03-18 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("catches", "0083_log_angler_log_private"),
    ]

    operations = [
        migrations.AlterField(
            model_name="log",
            name="angler",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
