# Generated by Django 4.2.7 on 2024-03-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catches", "0084_alter_log_angler"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fly",
            options={"ordering": ["fly_type", "name"]},
        ),
        migrations.AlterField(
            model_name="fly_type",
            name="image",
            field=models.ImageField(
                default=None, upload_to="fly_type/", verbose_name="Picture of fly type"
            ),
        ),
    ]
