# Generated by Django 4.2.7 on 2024-03-24 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catches", "0085_alter_fly_options_alter_fly_type_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bug",
            name="description",
        ),
    ]
