# Generated by Django 4.2.7 on 2024-03-28 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("catches", "0087_alter_bug_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lake",
            name="region",
        ),
        migrations.AddField(
            model_name="region",
            name="angler",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="region",
            name="lake",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="catches.lake",
            ),
        ),
    ]
