# Generated by Django 4.2.7 on 2024-03-28 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("catches", "0088_remove_lake_region_region_angler_region_lake"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="region",
            name="angler",
        ),
        migrations.RemoveField(
            model_name="region",
            name="lake",
        ),
        migrations.CreateModel(
            name="UserRegion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "angler",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="catches.region"
                    ),
                ),
            ],
        ),
    ]
