# Generated by Django 4.2.7 on 2024-03-28 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catches", "0089_remove_region_angler_remove_region_lake_userregion"),
    ]

    operations = [
        migrations.AddField(
            model_name="lake",
            name="regions",
            field=models.ManyToManyField(blank=True, to="catches.region"),
        ),
        migrations.AddField(
            model_name="region",
            name="lakes",
            field=models.ManyToManyField(blank=True, to="catches.lake"),
        ),
        migrations.DeleteModel(
            name="UserRegion",
        ),
    ]
