# Generated by Django 4.2.7 on 2024-03-29 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_remove_profile_regions"),
        ("catches", "0091_remove_lake_regions"),
    ]

    operations = [
        migrations.AddField(
            model_name="region",
            name="profile",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.profile",
            ),
            preserve_default=False,
        ),
    ]
