# Generated by Django 4.2.7 on 2024-04-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catches", "0092_region_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="region",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
