# Generated by Django 4.2.7 on 2024-04-05 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catches", "0094_alter_lake_options_remove_lake_favourite_favorite"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="favorite",
            options={"ordering": ["lake"]},
        ),
    ]
