# Generated by Django 4.2.7 on 2024-04-06 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catches", "0095_alter_favorite_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lake_id", models.IntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["notes"],
            },
        ),
    ]
