# Generated by Django 4.2.7 on 2024-04-16 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catches", "0096_announcment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fly",
            name="image",
            field=models.ImageField(
                blank=True,
                default="/public/assets/catches/site/default_fly.jpg",
                upload_to="flys/",
            ),
        ),
    ]
