# Generated by Django 4.2.7 on 2024-04-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catches", "0097_alter_fly_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fly",
            name="image",
            field=models.ImageField(
                blank=True, default="flys/default_fly.jpg", upload_to="flys/"
            ),
        ),
    ]
