# Generated by Django 4.2.7 on 2024-07-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catches", "0099_alter_stock_strain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="strain",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BEBE", "Beitty x Beitty"),
                    ("BRBE", "Bow River x Beitty"),
                    ("CLCL", "Campbell Lake"),
                    ("JLJL", "Job Lake"),
                    ("LYLY", "Lyndon"),
                    ("PLPL", "Pit Lake"),
                    ("TLTLJ", "Trout Lodge / Jumpers"),
                    ("TLTLK", "Trout Lodge / Kamloops"),
                    ("TLTLS", "Trout Lodge / Silvers"),
                    ("MCSW", "Marie Creek"),
                    ("LSE", "Lac Ste. Anne"),
                    ("JBL", "Job Lake"),
                    ("MC", "Marie Creek"),
                    ("RI", "Rock Island"),
                    ("AC", "Allison Creek"),
                    ("ACAC", "Westslope Cutthroat"),
                    ("RD", "Riverance"),
                    ("RVRV", "Riverance"),
                    ("MC", "Marie Creek"),
                    ("RI", "RockIsland"),
                ],
                max_length=100,
            ),
        ),
    ]
