# Generated by Django 4.2 on 2024-10-29 18:35

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ("catches", "0102_lake_reg_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="notes",
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="fish",
            name="image",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to="fish/",
                verbose_name="Picture of the fish",
            ),
        ),
    ]
