# Generated by Django 4.2 on 2024-10-15 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0102_lake_reg_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='fish/', verbose_name='Picture of the fish'),
        ),
    ]
