# Generated by Django 4.2 on 2024-10-29 18:37

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ("catches", "0103_alter_article_notes_alter_fish_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fish",
            name="notes",
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
