# Generated by Django 4.2 on 2024-10-29 21:11

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        (
            "catches",
            "0105_alter_bug_notes_alter_fly_notes_alter_fly_type_notes_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="region",
            name="notes",
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="video",
            name="notes",
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
