# Generated by Django 4.2 on 2024-11-11 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0106_alter_region_notes_alter_video_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='temp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='catches.temp'),
        ),
    ]
