# Generated by Django 4.2 on 2024-11-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catches", "0107_alter_log_temp"),
    ]

    operations = [
        migrations.AddField(
            model_name="week",
            name="ave_temp",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
