# Generated by Django 4.2 on 2024-11-14 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0103_alter_fish_image'),
        ('catches', '0108_week_ave_temp'),
    ]

    operations = [
    ]
