# Generated by Django 4.2 on 2026-05-11 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0109_merge_0103_alter_fish_image_0108_week_ave_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='strain',
            field=models.CharField(blank=True, choices=[('BEBE', 'Beitty x Beitty'), ('BRBE', 'Bow River x Beitty'), ('CLCL', 'Campbell Lake'), ('JLJL', 'Job Lake'), ('LYLY', 'Lyndon'), ('PLPL', 'Pit Lake'), ('TLTLJ', 'Trout Lodge / Jumpers'), ('TLTLK', 'Trout Lodge / Kamloops'), ('TLTLS', 'Trout Lodge / Silvers'), ('MCSW', 'Marie Creek'), ('LSE', 'Lac Ste. Anne'), ('JBL', 'Job Lake'), ('MC', 'Marie Creek'), ('RI', 'Rock Island'), ('AC', 'Allison Creek'), ('ACAC', 'Westslope Cutthroat'), ('RD', 'Riverance'), ('RVRV', 'Riverance'), ('MC', 'Marie Creek'), ('RI', 'RockIsland'), ('GL', 'Graham Lake'), ('EL', 'Ethel Lake')], max_length=100),
        ),
    ]
