# Generated by Django 4.2 on 2026-06-02 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0110_alter_stock_strain'),
    ]

    operations = [
        migrations.AddField(
            model_name='lake',
            name='size',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
