# Generated by Django 4.2 on 2026-06-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0111_lake_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='region',
            name='city',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='region',
            name='prov',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
