# Generated by Django 4.2 on 2026-06-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0112_region_address_region_city_region_prov'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='Lake_depth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='catch_depth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='gps_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='gps_long',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='city',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
