# Generated by Django 4.2 on 2026-06-29 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0113_log_lake_depth_log_catch_depth_log_gps_lat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='Lake_depth',
            new_name='lake_depth',
        ),
    ]
