# Generated by Django 4.2 on 2026-06-29 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0114_rename_lake_depth_log_lake_depth'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='catch_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
