# Generated by Django 4.2 on 2026-06-30 18:43

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0115_log_catch_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='catch_time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='log',
            name='record_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
