# Generated by Django 4.2 on 2026-07-01 03:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0116_alter_log_catch_time_alter_log_record_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='catch_time',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
