# Generated by Django 4.2 on 2026-07-01 03:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0117_alter_log_catch_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='catch_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
