# Generated by Django 4.2 on 2026-07-01 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0118_alter_log_catch_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.FloatField(blank=True, null=True)),
                ('feels_like', models.FloatField(blank=True, null=True)),
                ('pressure', models.FloatField(blank=True, null=True)),
                ('humidity', models.IntegerField(blank=True, null=True)),
                ('clouds', models.IntegerField(blank=True, null=True)),
                ('wind_speed', models.FloatField(blank=True, null=True)),
                ('wind_deg', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('icon', models.CharField(blank=True, max_length=20)),
                ('log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='weather', to='catches.log')),
            ],
        ),
    ]
