# Generated by Django 4.2 on 2026-09-04 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0119_logweather'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='log',
            name='fish_swami',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
