# Generated by Django 4.2 on 2026-09-04 23:27

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0120_category_alter_log_fish_swami'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.CreateModel(
            name='Knot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('notes', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Tying instructions, connection strength, and usage tips.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('articles', models.ManyToManyField(blank=True, help_text='Related reference guides or knot-testing articles.', related_name='knots', to='catches.article')),
                ('pictures', models.ManyToManyField(blank=True, help_text='Diagrams, tied examples, or step-by-step images.', related_name='knots', to='catches.picture')),
                ('videos', models.ManyToManyField(blank=True, help_text='Tutorial or tying demonstration videos.', related_name='knots', to='catches.video')),
            ],
            options={
                'verbose_name': 'Knot',
                'verbose_name_plural': 'Knots',
                'ordering': ['name'],
            },
        ),
    ]
