# Generated by Django 4.2 on 2026-09-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0121_alter_category_options_knot'),
    ]

    operations = [
        migrations.AddField(
            model_name='knot',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='knots/', verbose_name='Knot image'),
        ),
        migrations.AddField(
            model_name='knot',
            name='static_tag',
            field=models.SlugField(default='knot'),
            preserve_default=False,
        ),
    ]
