# Generated by Django 4.2 on 2026-09-05 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catches', '0122_knot_image_knot_static_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('model', models.CharField(blank=True, max_length=150, null=True)),
                ('brand', models.CharField(blank=True, max_length=150, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('manufacture_link', models.URLField(blank=True, null=True)),
                ('retailer_link', models.URLField(blank=True, null=True)),
                ('notes', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Equipment that you ar using.', null=True)),
                ('static_tag', models.SlugField()),
                ('charatristics', models.CharField(blank=True, max_length=300, null=True)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='lockers/', verbose_name='Locker image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('articles', models.ManyToManyField(blank=True, help_text='Related reference guides or knot-testing articles.', related_name='equipment_articles', to='catches.article')),
                ('catagory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catches.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pictures', models.ManyToManyField(blank=True, help_text='Diagrams, tied examples, or step-by-step images.', related_name='equipment_pictures', to='catches.picture')),
                ('videos', models.ManyToManyField(blank=True, help_text='Tutorial or tying demonstration videos.', related_name='equipment_videos', to='catches.video')),
            ],
            options={
                'verbose_name': 'locker',
                'verbose_name_plural': 'locker',
                'ordering': ['name'],
            },
        ),
    ]
