# Generated by Django 4.2 on 2026-09-05 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0123_locker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locker',
            name='static_tag',
        ),
    ]
