# Generated by Django 4.2 on 2026-09-05 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0124_remove_locker_static_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locker',
            old_name='catagory',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='locker',
            old_name='charatristics',
            new_name='characteristics',
        ),
    ]
