# Generated by Django 4.2 on 2026-09-05 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0125_rename_catagory_locker_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locker',
            name='manufacture_link',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='locker',
            name='retailer_link',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
    ]
