# Generated by Django 4.2 on 2026-09-05 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0126_alter_locker_manufacture_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locker',
            name='notes',
        ),
    ]
