# Generated by Django 4.2 on 2026-09-06 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catches', '0127_remove_locker_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('leader_length', models.CharField(blank=True, help_text='Length of leader, e.g. 9ft, 4ft, 7.5ft', max_length=50, null=True)),
                ('indicator_distance_from_fly_end', models.CharField(blank=True, help_text='Distance of strike indicator measured from the fly end of the leader (e.g. 18in, 3ft, 6ft)', max_length=50, null=True, verbose_name='Indicator distance from fly end of leader')),
                ('notes', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Setup details, casting notes, or specific fishing strategies.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('articles', models.ManyToManyField(blank=True, related_name='setups', to='catches.article')),
            ],
            options={
                'verbose_name': 'Line Setup',
                'verbose_name_plural': 'Line Setups',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='locker',
            options={'ordering': ['category', 'name'], 'verbose_name': 'locker', 'verbose_name_plural': 'locker'},
        ),
        migrations.CreateModel(
            name='SetupSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('length', models.CharField(blank=True, help_text='Length or distance, e.g. 4ft, 6in, 18in', max_length=50, null=True)),
                ('configuration', models.CharField(choices=[('main', 'Main Line (Point Fly)'), ('dropper', 'Y-Dropper / Tag Branch'), ('trailer', 'Trailing Fly Section')], default='main', max_length=50)),
                ('notes', models.CharField(blank=True, help_text="Notes for this section (e.g. 'Point fly', 'Top dropper', 'Trailing nymph')", max_length=200, null=True)),
                ('connection_knot', models.ForeignKey(blank=True, help_text="Knot connecting to this section (e.g. Blood Knot, Surgeon's, Clinch)", null=True, on_delete=django.db.models.deletion.SET_NULL, to='catches.knot')),
                ('hardware', models.ForeignKey(blank=True, help_text='Tippet ring, swivel, etc.', limit_choices_to={'category__name': 'Hardware'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_hardware', to='catches.locker')),
                ('setup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='catches.setup')),
                ('tippet_material', models.ForeignKey(blank=True, help_text='Tippet or leader material', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_tippets', to='catches.locker')),
            ],
            options={
                'verbose_name': 'Setup Section',
                'verbose_name_plural': 'Setup Sections',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='setup',
            name='fly_line',
            field=models.ForeignKey(blank=True, limit_choices_to={'category__name': 'Fly line'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setup_flylines', to='catches.locker'),
        ),
        migrations.AddField(
            model_name='setup',
            name='leader',
            field=models.ForeignKey(blank=True, limit_choices_to={'category__name': 'Leader'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setup_leaders', to='catches.locker'),
        ),
        migrations.AddField(
            model_name='setup',
            name='line_to_leader_knot',
            field=models.ForeignKey(blank=True, help_text='Knot connecting fly line to leader (e.g. Loop to Loop, Nail Knot)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setup_line_knots', to='catches.knot'),
        ),
        migrations.AddField(
            model_name='setup',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='setup',
            name='pictures',
            field=models.ManyToManyField(blank=True, related_name='setups', to='catches.picture'),
        ),
        migrations.AddField(
            model_name='setup',
            name='reel',
            field=models.ForeignKey(blank=True, limit_choices_to={'category__name': 'Reel'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setup_reels', to='catches.locker'),
        ),
        migrations.AddField(
            model_name='setup',
            name='rod',
            field=models.ForeignKey(blank=True, limit_choices_to={'category__name': 'Rod'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setup_rods', to='catches.locker'),
        ),
        migrations.AddField(
            model_name='setup',
            name='strike_indicator',
            field=models.ForeignKey(blank=True, limit_choices_to={'category__name': 'Hardware'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setup_indicators', to='catches.locker'),
        ),
        migrations.AddField(
            model_name='setup',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='setups', to='catches.video'),
        ),
    ]
