# Generated by Django 4.2 on 2026-09-06 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catches', '0128_setup_alter_locker_options_setupsection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='setup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='catches.setup'),
        ),
        migrations.AddField(
            model_name='setup',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Keep this setup private to your account or share with community'),
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('notes', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Strategy notes, retrieval technique, depth control, cadence, and tips.', null=True)),
                ('is_private', models.BooleanField(default=False, help_text='Keep this strategy private to your account or share with community')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('articles', models.ManyToManyField(blank=True, related_name='strategies', to='catches.article')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to=settings.AUTH_USER_MODEL)),
                ('pictures', models.ManyToManyField(blank=True, related_name='strategies', to='catches.picture')),
                ('setup', models.ForeignKey(blank=True, help_text='Rig setup used for this strategy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strategies', to='catches.setup')),
                ('videos', models.ManyToManyField(blank=True, related_name='strategies', to='catches.video')),
            ],
            options={
                'verbose_name': 'Fishing Strategy',
                'verbose_name_plural': 'Fishing Strategies',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='log',
            name='strategy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='catches.strategy'),
        ),
    ]
