# Generated by Django 4.2 on 2026-09-06 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0129_log_setup_setup_is_private_strategy_log_strategy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='temp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catches.temp'),
        ),
    ]
