# Generated by Django 4.2 on 2026-09-08 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catches', '0130_alter_log_temp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fly_type',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='bug',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='bug/', verbose_name='Picture of the bug'),
        ),
        migrations.AlterField(
            model_name='bug',
            name='static_tag',
            field=models.SlugField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='fish',
            name='static_tag',
            field=models.SlugField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='fly',
            name='static_tag',
            field=models.SlugField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='fly_type',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='fly_type/', verbose_name='Picture of fly type'),
        ),
        migrations.AlterField(
            model_name='hatch',
            name='static_tag',
            field=models.SlugField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='knot',
            name='static_tag',
            field=models.SlugField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='lake',
            name='static_tag',
            field=models.SlugField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='locker',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='setup',
            name='fly_line',
            field=models.ForeignKey(blank=True, limit_choices_to={'category__name__icontains': 'line'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setup_flylines', to='catches.locker'),
        ),
        migrations.AlterField(
            model_name='setup',
            name='leader',
            field=models.ForeignKey(blank=True, limit_choices_to={'category__name__icontains': 'leader'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setup_leaders', to='catches.locker'),
        ),
        migrations.AlterField(
            model_name='setup',
            name='reel',
            field=models.ForeignKey(blank=True, limit_choices_to={'category__name__icontains': 'reel'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setup_reels', to='catches.locker'),
        ),
        migrations.AlterField(
            model_name='setup',
            name='rod',
            field=models.ForeignKey(blank=True, limit_choices_to={'category__name__icontains': 'rod'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setup_rods', to='catches.locker'),
        ),
        migrations.AlterField(
            model_name='setup',
            name='strike_indicator',
            field=models.ForeignKey(blank=True, limit_choices_to={'category__name__icontains': 'hardware'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setup_indicators', to='catches.locker'),
        ),
        migrations.AlterField(
            model_name='temp',
            name='deg',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='temp',
            name='direction',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Post',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('title', models.CharField(max_length=100)),
                        ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                        ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                        ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                        ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                    ],
                    options={
                        'db_table': 'blog_post',
                        'ordering': ['-date_posted'],
                    },
                ),
            ],
            database_operations=[]
        ),
    ]
