# Generated by Django 4.2 on 2026-09-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0131_alter_fly_type_options_alter_bug_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='sort_order',
            field=models.IntegerField(blank=True, default=0, verbose_name='Sort order'),
        ),
    ]
