# Generated by Django 4.2 on 2026-09-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0132_alter_category_options_category_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup',
            name='setup_data',
            field=models.JSONField(blank=True, default=list, help_text='JSON representation of setup chain, droppers, and attachments', null=True),
        ),
    ]
