# Generated by Django 4.2 on 2026-09-11 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0133_setup_setup_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setup',
            name='fly_line',
        ),
        migrations.RemoveField(
            model_name='setup',
            name='indicator_distance_from_fly_end',
        ),
        migrations.RemoveField(
            model_name='setup',
            name='leader',
        ),
        migrations.RemoveField(
            model_name='setup',
            name='leader_length',
        ),
        migrations.RemoveField(
            model_name='setup',
            name='line_to_leader_knot',
        ),
        migrations.RemoveField(
            model_name='setup',
            name='reel',
        ),
        migrations.RemoveField(
            model_name='setup',
            name='rod',
        ),
        migrations.RemoveField(
            model_name='setup',
            name='strike_indicator',
        ),
        migrations.DeleteModel(
            name='SetupSection',
        ),
    ]
