# Generated by Django 4.2 on 2026-09-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0134_remove_setup_fly_line_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Updated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_stocked', models.DateField(auto_now=True)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='setup',
            name='setup_data',
            field=models.JSONField(blank=True, default=list, help_text='Rig sequence of components, droppers, and attachments', null=True),
        ),
    ]
